### ISSUE TITLE
VDSL3: simplified input of input files

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash#124]
What if you could use a module like this:

```groovy
workflow {
  Channel.fromPath("*.txt")
    | my_component
}
```

I.e. an element only contains a File, `map{ [ it.basename, it ] }` is automatically called. (if and only if `auto.simplifyInput` is true)

@tverbeiren Opinion?

**Comment by tverbeiren** [comment]
I'm on the fence about this.

It looks like an obvious thing to do and in fact there are few `test` workflows where I have this configured for convenience.

On the other hand:

1. Aren't we mixing pipeline arguments with component arguments? Shouldn't `simplifyInput` be an argument of the pipeline itself?
2. What if a user starts a pipeline that seems to work, but does not perform the expected analysis because the ID is not the correct one? Would the user know where things go wrong?

**Comment by rcannood** [comment]
Fair enough. Let's close thos.
